apiVersion: v1
kind: Pod
metadata:
  name: shay-flask
spec:
  containers:
  - name: flask
    image: shaylevin89perimeter/k-train:v1.0.1
    ports:
    - containerPort: $PORT
    env:
      - name: PORT
        value: $PORT