name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      semver_level:
        type: choice
        description: semver levek
        options:
        - major
        - minor
        - patch
        default: patch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REPO_NAME: shaylevin89perimeter
  DOCKER_IMAGE_NAME: k-train
  DOCKERHUB_USER: shaylevin89perimeter
  DOCKERHUB_PASSWD: ${{ secrets.DOCKERHUB_PASSWD }}
  MAKE_LATEST: true
  ENVIRONMENT: dev
  SEMVER_LEVEL: patch
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag $DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:v1.0.1
#    - name: show images
#      run: docker images
#    - name: docker login
#      run: echo $DOCKERHUB_PASSWD | docker login -u $DOCKERHUB_USER --password-stdin
#    - name: docker push
#      run: docker push $DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:v1.0.1
    - name: echo semver level
      run: echo ${{ github.event.inputs.semver_level }}
    - name: decide if default
      run: |
        if ${{ github.event.inputs.semver_level }}; then
          echo "SEMVER_LEVEL=${{ github.event.inputs.semver_level }}" >> $GITHUB_ENV
        else
          echo "SEMVER_LEVEL=$SEMVER_LEVEL" >> $GITHUB_ENV
        fi
    - name: get dockerhub token
      run: .github/scripts/get_last_tag.sh
    - name: get latest version
      run: echo $TOKEN