name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REPO_NAME: shaylevin89perimeter
  DOCKER_IMAGE_NAME: k-train
  ENVIRONMENT: dev
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test
    - name: show images
      run: docker images
